# Generated by Django 5.1.7 on 2025-03-27 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_bloodrequest_date'),
        ('donor', '0003_alter_blooddonate_id_alter_donor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='request_by_donor',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_gender',
            field=models.CharField(default='Not Specified', max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='patient_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BloodDonate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(default='None', max_length=100)),
                ('age', models.PositiveIntegerField(default=0)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('unit', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donations', to='donor.donor')),
            ],
        ),
    ]
